# docker-compose.yaml
version: '3.8'
services:
    jenkins:
        image: jenkins/jenkins:lts
        privileged: true
        user: root
        ports:
            - 8080:8080
            - 50000:50000
        container_name: jenkins
        volumes:
            - ./jenkins_configuration:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock

    #Sciezka javy w custom-jenkins-agent: /usr/lib/jvm/java-17-openjdk-amd64/bin/java
    agent:
        # image: jenkins/ssh-agent:jdk11
        image: custom-jenkins-agent
        privileged: true
        user: root
        container_name: agent
        expose:
            - 22
        environment:
            - JENKINS_AGENT_SSH_PUBKEY=